---

- name: set timezone
  ansible.builtin.template:
    src: timezone.j2
    dest: /etc/timezone
    owner: root
    group: root
    mode: "0644"
  become: True
  when: "ntp_timezone is defined"

- name: set localtime
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
    dest: /etc/localtime
    state: link
    force: True
    follow: False
  become: True
  when: "ntp_timezone is defined"

- name: install ntp
  ansible.builtin.apt:
    name: "{{ ntp_packages }}"
    state: present
    purge: True
    install_recommends: False
    autoremove: True
    update_cache: True
  become: True

- name: configure ntp
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  become: True
  notify:
    - restart ntp

- meta: flush_handlers

- name: enable and start ntp
  ansible.builtin.systemd:
    name: "{{ ntp_service_name }}"
    state: started
    enabled: True
  become: True
