---

- name: download | assert facts
  ansible.builtin.assert:
    that:
      - download_checksum_url is defined
      - download_checksum_dest is defined
      - download_url is defined
      - download_dest is defined

- name: download | get checksum
  ansible.builtin.get_url:
    url: "{{ download_checksum_url }}"
    dest: "{{ download_checksum_dest }}"
    owner: "{{ download_owner }}"
    group: "{{ download_group }}"
    mode: "{{ download_mode }}"
  become: True

- name: download | read checksum
  ansible.builtin.slurp:
    path: "{{ download_checksum_dest }}"
  register: download_checksum

- name: download | get file
  ansible.builtin.get_url:
    url: "{{ download_url }}"
    dest: "{{ download_dest }}"
    checksum: "{{ download_checksum_type }}:{{ download_checksum_item }}"
    owner: "{{ download_owner }}"
    group: "{{ download_group }}"
    mode: "{{ download_mode }}"
  become: True
  vars:
    download_checksum_content: "{{ download_checksum.content | b64decode }}"
    download_checksum_content_helper: "{{
      download_checksum_content | regex_search(download_checksum_regex, '\\1', multiline=True)
      if download_checksum_regex
      else download_checksum_content.split()[0]
    }}"
    download_checksum_item: "{{
      download_checksum_content
      if download_checksum_only
      else download_checksum_content_helper
    }}"
