---

- name: assert download vars
  ansible.builtin.assert:
    that:
      - download_checksum_url is defined
      - download_url is defined
      - download_dest is defined

- name: download file
  ansible.builtin.get_url:
    url: "{{ download_url }}"
    dest: "{{ download_dest }}"
    checksum: "{{ download_checksum_type }}:{{ download_checksum_item }}"
    owner: "{{ download_owner }}"
    group: "{{ download_group }}"
    mode: "{{ download_mode }}"
  become: True
  vars:
    download_checksum_content: "{{ lookup('ansible.builtin.url', download_checksum_url, split_lines=False) }}"
    download_checksum_content_helper: "{{
      download_checksum_content | regex_search(download_checksum_regex, '\\1', multiline=True)
      if download_checksum_regex
      else download_checksum_content.split()[0]
    }}"
    download_checksum_item: "{{
      download_checksum_content
      if download_checksum_only
      else download_checksum_content_helper
    }}"
