---

- name: check kubernetes-release version
  ansible.builtin.debug:
    msg: "kubernetes-release update available: {{ kubernetes_release_version }} -> {{ kubernetes_release_repo | mikavl.ansible.gh_latest }}"
  when: "not kubernetes_release_version | mikavl.ansible.gh_is_latest(kubernetes_release_repo)"
  tags: [ kubernetes_release, version ]

- name: create kubernetes-release config dir
  ansible.builtin.file:
    path: "{{ kubernetes_release_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: True

- name: download kubernetes-release
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    force: True
    owner: root
    group: root
    mode: 0644
  become: True
  loop:
    - url: "{{ kubernetes_release_service_url }}"
      dest: "{{ kubernetes_release_service_path }}"
    - url: "{{ kubernetes_release_config_url }}"
      dest: "{{ kubernetes_release_config_path }}"
  notify:
    - kubernetes-release reload

- meta: flush_handlers

- name: enable kubernetes-release
  ansible.builtin.systemd:
    name: "{{ kubernetes_release_service_name }}"
    enabled: True
  become: True
