---

- name: check kubelet version
  ansible.builtin.debug:
    msg: "kubelet update available: {{ kubelet_version }} -> {{ kubelet_label | mikavl.ansible.kube_latest }}"
  when: "not kubelet_version | mikavl.ansible.kube_is_latest(kubelet_label)"

- name: download kubelet
  ansible.builtin.get_url:
    url: "{{ kubelet_url }}"
    dest: "{{ kubelet_path }}"
    checksum: "sha256:{{ kubelet_checksum }}"
    owner: root
    group: root
    mode: 0755
  become: True
