---

- name: copy kubelet binary
  ansible.builtin.copy:
    src: "{{ kubelet_binary_path }}"
    dest: /usr/local/bin/kubelet
    remote_src: True
    owner: root
    group: root
    mode: "0755"
  become: True
