---

dependencies:
  - role: cache
  - role: download
    vars:
      download_checksum_url: "{{ kubelet_binary_checksum_url }}"
      download_checksum_dest: "{{ kubelet_binary_checksum_path }}"
      download_checksum_only: True
      download_url: "{{ kubelet_binary_url }}"
      download_dest: "{{ kubelet_binary_path }}"
