---

kubectl_system: "{{ ansible_system | lower }}"
kubectl_architecture: "{{ {
  'aarch64': 'arm64',
  'x86_64': 'amd64',
} [ansible_architecture] }}"

kubectl_url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/{{ kubectl_system }}/{{ kubectl_architecture }}/kubectl"
kubectl_path: "/usr/local/bin/kubectl"

kubectl_checksum_url: "{{ kubectl_url }}.sha256"
kubectl_checksum: "{{ lookup('ansible.builtin.url', kubectl_checksum_url) }}"
