---

cni_plugins_system: "{{ ansible_system | lower }}"
cni_plugins_architecture: "{{ {
  'aarch64': 'arm64',
  'x86_64': 'amd64',
} [ansible_architecture] }}"

cni_plugins_repo: "containernetworking/plugins"

cni_plugins_url: "https://github.com/{{ cni_plugins_repo }}/releases/download/v{{ cni_plugins_version }}/cni-plugins-{{ cni_plugins_system }}-{{ cni_plugins_architecture }}-v{{ cni_plugins_version }}.tgz"
cni_plugins_path: "{{ cni_plugins_cache_dir }}/{{ cni_plugins_url | basename }}"

cni_plugins_dir: "/opt/cni/bin"

cni_plugins_checksum_url: "{{ cni_plugins_url }}.sha256"
cni_plugins_checksum: "{{ lookup('ansible.builtin.url', cni_plugins_checksum_url).split() | first }}"
