---

- name: check cni-plugins version
  ansible.builtin.debug:
    msg: "cni-plugins update available: {{ cni_plugins_version }} -> {{ cni_plugins_repo | gh_latest }}"
  when: "not cni_plugins_version | gh_is_latest(cni_plugins_repo)"

- name: download cni-plugins
  ansible.builtin.get_url:
    url: "{{ cni_plugins_url }}"
    dest: "{{ cni_plugins_path }}"
    checksum: "sha256:{{ cni_plugins_checksum }}"
    owner: root
    group: root
    mode: 0644
  become: True

- name: create cni-plugins dir
  ansible.builtin.file:
    path: "{{ cni_plugins_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: True

- name: unarchive cni-plugins
  ansible.builtin.unarchive:
    src: "{{ cni_plugins_path }}"
    dest: "{{ cni_plugins_dir }}"
    remote_src: True
    owner: root
    group: root
    mode: "0755"
  become: True
