---

- name: create cni-plugins dir
  ansible.builtin.file:
    path: "{{ cni_plugins_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: True

- name: unarchive cni-plugins
  ansible.builtin.unarchive:
    src: "{{ cni_plugins_dest }}"
    dest: "{{ cni_plugins_dir }}"
    include:
      - bin/*
    remote_src: True
    owner: root
    group: root
    mode: "0755"
  become: True
