---

- name: check cni-plugins version
  ansible.builtin.include_role:
    name: github_version
  vars:
    github_version_current: "{{ cni_plugins_version }}"
    github_version_repo: "{{ cni_plugins_repo }}"

- name: create cni-plugins dir
  ansible.builtin.file:
    path: "{{ cni_plugins_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: True

- name: extract cni-plugins
  ansible.builtin.include_role:
    name: extract
  vars:
    extract_src: "{{ cni_plugins_archive_path }}"
    extract_dest: "{{ cni_plugins_dir }}"
    extract_mode: "0755"
