---

- name: download cni-plugins
  ansible.builtin.get_url:
    url: "{{ cni_plugins_url }}"
    dest: "{{ cni_plugins_dest }}"
    checksum: "sha256:{{ cni_plugins_checksum }}"
    owner: root
    group: root
    mode: 0644
  become: True

- name: create cni-plugins dir
  ansible.builtin.file:
    path: "{{ cni_plugins_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: True

- name: unarchive cni-plugins
  ansible.builtin.unarchive:
    src: "{{ cni_plugins_dest }}"
    dest: "{{ cni_plugins_dir }}"
    remote_src: True
    owner: root
    group: root
    mode: "0755"
  become: True
