---

- name: check kubectl version
  ansible.builtin.debug:
    msg: "kubectl update available: {{ kubectl_version }} -> {{ kubectl_label | kube_latest }}"
  when: "not kubectl_version | kube_is_latest(kubectl_label)"

- name: download kubectl
  ansible.builtin.get_url:
    url: "{{ kubectl_url }}"
    dest: "{{ kubectl_path }}"
    checksum: "sha256:{{ kubectl_checksum }}"
    owner: root
    group: root
    mode: 0755
  become: True
