---

- name: copy kubectl binary
  ansible.builtin.copy:
    src: "{{ kubectl_binary_path }}"
    dest: /usr/local/bin/kubectl
    remote_src: True
    owner: root
    group: root
    mode: "0755"
  become: True
