---

- name: assert extract vars
  ansible.builtin.assert:
    that:
      - extract_src is defined
      - extract_dest is defined

- name: create temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: extract_tempfile
  changed_when: False

- block:

    - name: unarchive file
      ansible.builtin.unarchive:
        src: "{{ extract_src }}"
        dest: "{{ extract_tempfile.path }}"
        remote_src: True
      changed_when: False

    - name: find extracted files
      ansible.builtin.find:
        path: "{{ extract_tempfile.path }}{{ extract_subpath }}"
        patterns: "{{ extract_patterns }}"
      register: extract_find

    - name: copy extracted files
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "{{ extract_dest }}/{{ extract_filename }}"
        remote_src: True
        owner: "{{ extract_owner }}"
        group: "{{ extract_group }}"
        mode: "{{ extract_mode }}"
      become: True
      loop: "{{ extract_find.files }}"
      loop_control:
        label: "{{ extract_filename }}"
      vars:
        extract_filename: "{{ item.path | basename }}"

  always:

    - name: remove temporary directory
      ansible.builtin.file:
        path: "{{ extract_tempfile.path }}"
        state: absent
      changed_when: False
