---

runc_architecture: "{{ {
  'aarch64': 'arm64',
  'x86_64': 'amd64',
} [ansible_architecture] }}"

runc_repo: "opencontainers/runc"

runc_url: "https://github.com/{{ runc_repo }}/releases/download/v{{ runc_version }}/runc.{{ runc_architecture }}"
runc_path: "/usr/local/bin/runc"

runc_checksums_url: "{{ runc_url | dirname }}/runc.sha256sum"

runc_checksum_regex: '^([a-z0-9]+)\s+runc\.{{ runc_architecture }}$'
runc_checksum: "{{ lookup('ansible.builtin.url', runc_checksums_url) | regex_search(runc_checksum_regex, '\\1', multiline=True) }}"
