---

containerd_architecture: "{{ {
  'aarch64': 'arm64',
  'x86_64': 'amd64',
} [ansible_architecture] }}"

containerd_config_dir: /etc/containerd

containerd_config_dest: "{{ containerd_config_dir }}/config.toml"

containerd_system: "{{ ansible_system | lower }}"

containerd_repo: "containerd/containerd"

containerd_url: "https://github.com/{{ containerd_repo }}/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-{{ containerd_system }}-{{ containerd_architecture }}.tar.gz"
containerd_dest: "{{ containerd_cache_dir }}/{{ containerd_url | basename }}"

containerd_checksum_url: "{{ containerd_url }}.sha256sum"
containerd_checksum_dest: "{{ containerd_dest }}.sha256sum"

containerd_service_url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"

containerd_service_name: "{{ containerd_service_url | basename }}"

containerd_service_dest: "/etc/systemd/system/{{ containerd_service_name }}"
