---

kubeadm_system: "{{ ansible_system | lower }}"
kubeadm_architecture: "{{ {
  'aarch64': 'arm64',
  'x86_64': 'amd64',
} [ansible_architecture] }}"

kubeadm_label: "stable"

kubeadm_url: "https://dl.k8s.io/release/v{{ kubeadm_version }}/bin/{{ kubeadm_system }}/{{ kubeadm_architecture }}/kubeadm"
kubeadm_path: "/usr/local/bin/kubeadm"

kubeadm_checksum_url: "{{ kubeadm_url }}.sha256"
kubeadm_checksum: "{{ lookup('ansible.builtin.url', kubeadm_checksum_url) }}"

kubeadm_packages:
  - apparmor
  - conntrack
  - ethtool
  - iptables
  - socat

kubeadm_modules:
  - br_netfilter

kubeadm_sysctl_variables:
  net.ipv4.ip_forward: "1"
