---

dependencies:
  - role: github_version
    vars:
      github_version_current: "{{ runc_version }}"
      github_version_repo: "{{ runc_repo }}"
  - role: cache
  - role: download
    vars:
      download_checksum_url: "{{ runc_binary_checksums_url }}"
      download_checksum_dest: "{{ runc_binary_checksums_path }}"
      download_checksum_regex: '^([a-z0-9]+)\s+runc\.{{ runc_architecture }}$'
      download_url: "{{ runc_binary_url }}"
      download_dest: "{{ runc_binary_path }}"
