---

- name: containerd | systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: True

- name: containerd | systemctl restart
  ansible.builtin.systemd:
    name: "{{ containerd_systemd_service_name }}"
    state: restarted
