---

- name: reload containerd
  ansible.builtin.systemd:
    daemon_reload: True
  become: True

- name: restart containerd
  ansible.builtin.systemd:
    name: "{{ containerd_systemd_service_name }}"
    state: restarted
  become: True
