---

- name: check cri-tools version
  ansible.builtin.include_role:
    name: github_version
  vars:
    github_version_current: "{{ cri_tools_version }}"
    github_version_repo: "{{ cri_tools_repo }}"

- name: download cri-tools
  ansible.builtin.include_role:
    name: download
  vars:
    download_checksum_url: "{{ cri_tools_archive_checksum_url }}"
    download_checksum_dest: "{{ cri_tools_archive_checksum_path }}"
    download_url: "{{ cri_tools_archive_url }}"
    download_dest: "{{ cri_tools_archive_path }}"

- name: extract cri-tools
  ansible.builtin.include_role:
    name: extract
  vars:
    extract_src: "{{ cri_tools_archive_path }}"
    extract_dest: /usr/local/bin
    extract_patterns: crictl
    extract_mode: "0755"
