---

- name: check cri-tools version
  ansible.builtin.debug:
    msg: "cri-tools update available: {{ cri_tools_version }} -> {{ cri_tools_repo | mikavl.ansible.gh_latest }}"
  when: "not cri_tools_version | mikavl.ansible.gh_is_latest(cri_tools_repo)"

- name: download cri-tools
  ansible.builtin.get_url:
    url: "{{ cri_tools_url }}"
    dest: "{{ cri_tools_path }}"
    checksum: "sha256:{{ cri_tools_checksum }}"
    owner: root
    group: root
    mode: 0644
  become: True

- name: unarchive cri-tools
  ansible.builtin.unarchive:
    src: "{{ cri_tools_path }}"
    dest: "{{ cri_tools_dir }}"
    remote_src: True
    owner: root
    group: root
    mode: 0755
  become: True
