---

- name: runc | version check
  ansible.builtin.include_role:
    name: github_version
  vars:
    github_version_current: "{{ runc_version }}"
    github_version_repo: "{{ runc_repo }}"

- name: runc | create archive directory
  ansible.builtin.file:
    path: "{{ runc_archive_dir }}"
    state: directory

- name: runc | download archive
  ansible.builtin.include_role:
    name: download
  vars:
    download_checksum_url: "{{ runc_binary_checksums_url }}"
    download_checksum_dest: "{{ runc_binary_checksums_path }}"
    download_checksum_regex: '^([a-z0-9]+)\s+runc\.{{ runc_architecture }}$'
    download_url: "{{ runc_binary_url }}"
    download_dest: "{{ runc_binary_path }}"

- name: runc | copy binary
  ansible.builtin.copy:
    src: "{{ runc_binary_path }}"
    dest: /usr/local/bin/runc
    remote_src: True
    mode: "0755"
