---

- name: check runc version
  ansible.builtin.debug:
    msg: "runc update available: {{ runc_version }} -> {{ runc_repo | mikavl.ansible.gh_latest }}"
  when: "not runc_version | mikavl.ansible.gh_is_latest(runc_repo)"

- name: download runc
  ansible.builtin.get_url:
    url: "{{ runc_url }}"
    dest: "{{ runc_path }}"
    checksum: "sha256:{{ runc_checksum }}"
    owner: root
    group: root
    mode: 0755
  become: True
