---

- name: copy runc binary
  ansible.builtin.copy:
    src: "{{ runc_binary_path }}"
    dest: /usr/local/bin/runc
    remote_src: True
    owner: root
    group: root
    mode: "0755"
  become: True
