---

- name: check runc version
  ansible.builtin.include_role:
    name: github_version
  vars:
    github_version_current: "{{ runc_version }}"
    github_version_repo: "{{ runc_repo }}"

- name: create runc cache dir
  ansible.builtin.file:
    path: "{{ runc_archive_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: True

- name: download runc
  ansible.builtin.include_role:
    name: download
  vars:
    download_checksum_url: "{{ runc_binary_checksums_url }}"
    download_checksum_dest: "{{ runc_binary_checksums_path }}"
    download_checksum_regex: '^([a-z0-9]+)\s+runc\.{{ runc_architecture }}$'
    download_url: "{{ runc_binary_url }}"
    download_dest: "{{ runc_binary_path }}"

- name: copy runc binary
  ansible.builtin.copy:
    src: "{{ runc_binary_path }}"
    dest: /usr/local/bin/runc
    remote_src: True
    owner: root
    group: root
    mode: "0755"
  become: True
