name: Ansible

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set python3 as default
        run: sudo apt-get update && sudo apt-get install --assume-yes --no-install-recommends python-is-python3
      - name: Configure Ansible
        run: echo -e "[defaults]\nfilter_plugins = filter_plugins\nroles_path = roles" > ansible.cfg
      - name: Run playbooks
        run: >
          ansible-playbook playbooks/*.yml
          --connection local
          --inventory "localhost,"
          --extra-vars "targets=localhost"
