name: Ansible

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ansible:
    strategy:
      matrix:
        playbook:
          - cni_plugins
          - containerd
          - cri_tools
          - kubeadm
          - kubectl
          - kubelet
          - runc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          pipx inject ansible-core requests
      - uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/${{ matrix.playbook }}.yml
          inventory: |
            localhost
          options: |
            --connection local
            --extra-vars targets=localhost
