name: Ansible

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx list
      - run: |
          pipx install ansible-base
          pipx inject ansible-base requests
      - uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/containerd.yml
          inventory: |
            localhost
          options: |
            --connection local
            --extra-vars targets=localhost
