---

- name: containerd | create archive directory
  ansible.builtin.file:
    path: "{{ containerd_archive_dir }}"
    state: directory

- name: containerd | download archive
  ansible.builtin.include_role:
    name: download
  vars:
    download_checksum_url: "{{ containerd_archive_checksum_url }}"
    download_checksum_dest: "{{ containerd_archive_checksum_path }}"
    download_url: "{{ containerd_archive_url }}"
    download_dest: "{{ containerd_archive_path }}"

- name: containerd | extract archive
  ansible.builtin.include_role:
    name: extract
  vars:
    extract_src: "{{ containerd_archive_path }}"
    extract_subpath: /bin
    extract_dest: /usr/local/bin
    extract_mode: "0755"

- name: containerd | download systemd service unit file
  ansible.builtin.get_url:
    url: "{{ containerd_systemd_service_unit_file_url }}"
    dest: "{{ containerd_systemd_service_unit_file_path }}"
  notify:
    - containerd | systemctl daemon-reload
    - containerd | systemctl restart

- name: containerd | create configuration directory
  ansible.builtin.file:
    path: "{{ containerd_config_dir }}"
    state: directory

- name: containerd | create configuration file
  ansible.builtin.template:
    src: config.toml.j2
    dest: "{{ containerd_config_path }}"
  notify:
    - containerd | systemctl restart

- meta: flush_handlers

- name: containerd | enable and start systemd service
  ansible.builtin.systemd:
    name: "{{ containerd_systemd_service_name }}"
    state: started
    enabled: True
