---

- name: unarchive containerd
  ansible.builtin.unarchive:
    src: "{{ containerd_dest }}"
    dest: "{{ containerd_dir }}"
    remote_src: True
    include:
      - bin/*
    owner: root
    group: root
    mode: "0755"
  become: True

- name: download containerd systemd service unit file
  ansible.builtin.get_url:
    url: "{{ containerd_service_url }}"
    dest: "{{ containerd_service_dest }}"
    owner: root
    group: root
    mode: "0644"
  become: True
  notify:
    - reload containerd
    - restart containerd

- name: create containerd config dir
  ansible.builtin.file:
    path: "{{ containerd_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: True

- name: configure containerd
  ansible.builtin.template:
    src: config.toml.j2
    dest: "{{ containerd_config_dest }}"
    owner: root
    group: root
    mode: "0644"
  become: True
  notify:
    - restart containerd

- meta: flush_handlers

- name: enable and start containerd
  ansible.builtin.systemd:
    name: "{{ containerd_service_name }}"
    state: started
    enabled: True
  become: True
